# Generated by Django 2.1.1 on 2018-09-13 08:37

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('discription', models.TextField(max_length=800)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=event.models.image_name)),
            ],
        ),
        migrations.AddField(
            model_name='confrence',
            name='speakers',
            field=models.ManyToManyField(to='event.Speaker'),
        ),
    ]
