# Generated by Django 2.1.1 on 2018-09-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='confrence',
            name='discription',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Speaker'),
        ),
    ]
