# Generated by Django 2.1.1 on 2018-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180913_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
