# Generated by Django 2.1.1 on 2018-09-13 21:54

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180913_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=event.models.image_name),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
