# Generated by Django 2.1.1 on 2018-09-13 21:57

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180914_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='visitor',
            name='qxzcq23r_code',
            field=models.ImageField(blank=True, upload_to=event.models.image_name),
        ),
    ]
