# Generated by Django 2.1.1 on 2018-09-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180914_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='qxzcq23r_code',
            new_name='qrcvcode',
        ),
    ]
