# Generated by Django 2.1.1 on 2018-09-13 22:20

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_visitor_qrcvcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='comptany',
            new_name='company',
        ),
        migrations.AddField(
            model_name='visitor',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=event.models.image_name),
        ),
    ]
