# Generated by Django 2.1.1 on 2018-10-06 17:35

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180914_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, upload_to=event.models.image_name),
        ),
    ]
