# Generated by Django 2.0.9 on 2018-12-01 11:25

import django.core.validators
from django.db import migrations, models
import django_google_maps.fields
import events.utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181129_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(default=2018, editable=False, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, help_text='XX.XXX ,YY.YYYY', max_length=100, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(blank=True, upload_to=events.utils.image_name, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название места'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='location',
            name='web_site',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
