# Generated by Django 2.1 on 2018-09-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.Cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_adress',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
