# Generated by Django 2.0.9 on 2019-01-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190116_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Govno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govno', models.CharField(max_length=52)),
            ],
        ),
    ]
