# Generated by Django 2.0.9 on 2019-02-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(choices=[('woman', 'Жене'), ('girlfriend', 'Девушке'), ('mom', 'Маме'), ('dad', 'Папе'), ('boss', 'Начальнику')], max_length=30)),
                ('occasion', models.CharField(choices=[('bd', 'Дня рождения'), ('ny', 'Нового года')], max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
