from setuptools import setup

setup(
    name='rent_space',
    version='',
    packages=['==16.1.0.Lib.distutils', '==16.1.0.Lib.encodings', '==16.1.0.Lib.importlib', '==16.1.0.Lib.collections',
              '==16.1.0.Lib.site-packages.pip', '==16.1.0.Lib.site-packages.pip._vendor',
              '==16.1.0.Lib.site-packages.pip._vendor.idna', '==16.1.0.Lib.site-packages.pip._vendor.pep517',
              '==16.1.0.Lib.site-packages.pip._vendor.pytoml', '==16.1.0.Lib.site-packages.pip._vendor.certifi',
              '==16.1.0.Lib.site-packages.pip._vendor.chardet', '==16.1.0.Lib.site-packages.pip._vendor.chardet.cli',
              '==16.1.0.Lib.site-packages.pip._vendor.distlib',
              '==16.1.0.Lib.site-packages.pip._vendor.distlib._backport',
              '==16.1.0.Lib.site-packages.pip._vendor.msgpack', '==16.1.0.Lib.site-packages.pip._vendor.urllib3',
              '==16.1.0.Lib.site-packages.pip._vendor.urllib3.util',
              '==16.1.0.Lib.site-packages.pip._vendor.urllib3.contrib',
              '==16.1.0.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              '==16.1.0.Lib.site-packages.pip._vendor.urllib3.packages',
              '==16.1.0.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              '==16.1.0.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              '==16.1.0.Lib.site-packages.pip._vendor.colorama', '==16.1.0.Lib.site-packages.pip._vendor.html5lib',
              '==16.1.0.Lib.site-packages.pip._vendor.html5lib._trie',
              '==16.1.0.Lib.site-packages.pip._vendor.html5lib.filters',
              '==16.1.0.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              '==16.1.0.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              '==16.1.0.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              '==16.1.0.Lib.site-packages.pip._vendor.lockfile', '==16.1.0.Lib.site-packages.pip._vendor.progress',
              '==16.1.0.Lib.site-packages.pip._vendor.requests', '==16.1.0.Lib.site-packages.pip._vendor.packaging',
              '==16.1.0.Lib.site-packages.pip._vendor.cachecontrol',
              '==16.1.0.Lib.site-packages.pip._vendor.cachecontrol.caches',
              '==16.1.0.Lib.site-packages.pip._vendor.webencodings',
              '==16.1.0.Lib.site-packages.pip._vendor.pkg_resources', '==16.1.0.Lib.site-packages.pip._internal',
              '==16.1.0.Lib.site-packages.pip._internal.cli', '==16.1.0.Lib.site-packages.pip._internal.req',
              '==16.1.0.Lib.site-packages.pip._internal.vcs', '==16.1.0.Lib.site-packages.pip._internal.utils',
              '==16.1.0.Lib.site-packages.pip._internal.models', '==16.1.0.Lib.site-packages.pip._internal.commands',
              '==16.1.0.Lib.site-packages.pip._internal.operations', '==16.1.0.Lib.site-packages.wheel',
              '==16.1.0.Lib.site-packages.wheel.cli', '==16.1.0.Lib.site-packages.setuptools',
              '==16.1.0.Lib.site-packages.setuptools.extern', '==16.1.0.Lib.site-packages.setuptools._vendor',
              '==16.1.0.Lib.site-packages.setuptools._vendor.packaging',
              '==16.1.0.Lib.site-packages.setuptools.command', '==16.1.0.Lib.site-packages.pkg_resources',
              '==16.1.0.Lib.site-packages.pkg_resources.extern', '==16.1.0.Lib.site-packages.pkg_resources._vendor',
              '==16.1.0.Lib.site-packages.pkg_resources._vendor.packaging', 'rent_space', 'rental_api',
              'rental_api.migrations'],
    url='',
    license='',
    author='Nikita',
    author_email='',
    description=''
)
