# Generated by Django 2.1.1 on 2018-10-02 14:09

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('slug', models.SlugField()),
                ('venue_name', models.CharField(max_length=150)),
                ('venue_url', models.URLField()),
                ('poster', models.ImageField(upload_to=mainapp.models.poster_name)),
            ],
        ),
    ]
