# Generated by Django 2.1.1 on 2018-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
