# Generated by Django 2.1.1 on 2018-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20180929_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=150)),
                ('two', models.CharField(max_length=150)),
                ('three', models.CharField(max_length=150)),
                ('four', models.CharField(max_length=150)),
                ('five', models.CharField(max_length=150)),
                ('six', models.CharField(max_length=150)),
                ('seven', models.CharField(max_length=150)),
                ('eight', models.CharField(max_length=150)),
                ('nine', models.CharField(max_length=150)),
                ('ten', models.CharField(max_length=150)),
            ],
        ),
    ]
