# Generated by Django 2.1.1 on 2018-09-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ten',
        ),
    ]
