# Generated by Django 2.1.1 on 2018-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_remove_test_ten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=150)),
                ('two', models.CharField(max_length=150)),
                ('three', models.CharField(max_length=150)),
                ('four', models.CharField(max_length=150)),
                ('five', models.CharField(max_length=150)),
            ],
        ),
    ]
